### ISSUE TITLE
Multiple lang and other parameter

### ISSUE THREAD

**Issue by nam-co** [berkayk/laravel-onesignal#1]
Hi Berkayk, thanks for this package, I was wondering how can I specify messages in multiple languages and a delivery_time_of_day parameter?

is it possible to use this:
$content = array("en" => 'English Message',"es" => 'Spanish Message');
$data = array("delivery_time_of_day" => '9:00AM');
OneSignal::sendNotificationToAll($content, $url, $data);

Appreciate any help you can give me
Thanks

**Comment by berkayk** [comment]
Hi nam-co, I haven't created a wrapper method for that specific purpose, but I'm planning to extend this package with more useful methods. You can always use `sendNotificationCustom ` method for your specific needs. For your question, you can try the following.

    // Initialize parameters
    $params = [];
    $contents = ["en" => 'English Message',"es" => 'Spanish Message'];
    $params["contents"] = $contents;
    $params["delayed_option"] = "timezone";
    $params["delivery_time_of_day"] = "09:00 AM";
    // Below are optional
    $params["url"] = $url;
    OneSignal::sendNotificationCustom($params);

Before trying this, please update your version to `v0.9.1`

.

If you need additional help, do not hesitate to ask :)

**Comment by nam-co** [comment]
Thanks Berkayk, I will test and let you know
