### ISSUE TITLE
sendNotificationToExternalUser function not coming if we install with composer

### ISSUE THREAD

**Issue by satishnreddy999** [berkayk/laravel-onesignal#105]
Hi, 
when i install the package using composer as per the documentation, the function sendNotificationToExternalUser is missing. when i see in github the function is there. Please fix the issue. thanx

**Comment by Zontir** [comment]
Same

**Comment by Jipem** [comment]
sendNotificationToExternalUser() does not exist in vendor\berkayk\onesignal-laravel\src\OneSignalClient.php
@berkayk, please new realease for update via composer :-)

**Comment by berkayk** [comment]
Just released a new version (v1.0.2)

**Comment by Jipem** [comment]
Thank you so much !
