### ISSUE TITLE
OneSignal::setParam('headings', $headings) is sending notification twice

### ISSUE THREAD

**Issue by shunyauads** [berkayk/laravel-onesignal#106]
When using the code below, one signal is sending the notification two times.
```
OneSignal::setParam('headings', $headings)
                    ->sendNotificationToAll (
                        $body,
                        $url = null,
                        $data = $dataToNotify,
                        $buttons = null,
                        $schedule = null
                    );
```

**Comment by Appsbender** [comment]
Try this one. 
        `OneSignal::sendNotificationToAll(
            'You message',
            'player id',
            null,
            null,
            null,
            array(
                "en" => "Custom Header Name"
           ));`

**Comment by CrackiGuy** [comment]
OneSignal::sendNotificationToAll(
               "This is message.",
                $url = null,
                $data = null,
                $buttons = null, 
                $schedule = null,
                $headings  = "Heading is here"
            );
