### ISSUE TITLE
I cannot call 'OneSignal'

### ISSUE THREAD

**Issue by erdemnagikho** [berkayk/laravel-onesignal#107]
Hi people, i cannot call 'OneSignal' and because of this i cannot use methods. I did install it step by step.

**Comment by Abubakr077** [comment]
same error with me.
I have added allies and providers lines too. tried all the previous threads solutions too with the same question.

**Comment by Appsbender** [comment]
Please find below the quickest solution you can use. 

`$client = new Berkayk\OneSignal\OneSignalClient(
            'APP_ID',
            'REST_API_KEY',
            'USER_AUTH_KEY';
$client->sendNotificationToUser(
            'message',
            'player Id'
        );`

**Comment by Tuapplicacion** [comment]
I have this same error...

**Comment by Jnlbr** [comment]
I have this same error.

**Comment by Jnlbr** [comment]
Ok, in top of the file I added "use OneSignal", and it works.
