### ISSUE TITLE
Specifying Message Title, and body

### ISSUE THREAD

**Issue by fradrick** [berkayk/laravel-onesignal#110]
I am just wondering, how exactly to achieve this.

Basically I need to provide the **message title** and **message body/details**, 
as shown here: 

![msg](https://user-images.githubusercontent.com/31401736/61947080-8ad19880-afa4-11e9-8b7b-6ed7441b4631.PNG)

but this doesn't seem straight forward, at least for me.

Equally how to add these **other attributes**, or specifically their names:

![attr](https://user-images.githubusercontent.com/31401736/61946964-3f1eef00-afa4-11e9-99ba-4e51f99b448b.PNG)

**Comment by berkayk** [comment]
Please see `sendNotificationCustom` method. Available parameters to explore are referenced [here](https://documentation.onesignal.com/reference#section-common-parameters).

**Comment by fradrick** [comment]
Noted, I got it working, let me close the issue
