### ISSUE TITLE
Error while $  composer require berkayk/onesignal-laravel

### ISSUE THREAD

**Issue by webdev-code** [berkayk/laravel-onesignal#114]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel-notification-channels/onesignal 1.2.0 requires berkayk/onesignal-laravel ^0.9.3 -> satisfiable by berkayk/onesignal-laravel[0.9.8, 0.9.9, v0.9.3, v0.9.4, v0.9.5, v0.9.6, v0.9.7] but these conflict with your requirements or minimum-stability.
    - laravel-notification-channels/onesignal 1.2.0 requires berkayk/onesignal-laravel ^0.9.3 -> satisfiable by berkayk/onesignal-laravel[0.9.8, 0.9.9, v0.9.3, v0.9.4, v0.9.5, v0.9.6, v0.9.7] but these conflict with your requirements or minimum-stability.
    - laravel-notification-channels/onesignal 1.2.0 requires berkayk/onesignal-laravel ^0.9.3 -> satisfiable by berkayk/onesignal-laravel[0.9.8, 0.9.9, v0.9.3, v0.9.4, v0.9.5, v0.9.6, v0.9.7] but these conflict with your requirements or minimum-stability.
    - Installation request for laravel-notification-channels/onesignal (locked at 1.2.0, required as ^1.2) -> satisfiable by laravel-notification-channels/onesignal[1.2.0].

Installation failed, reverting ./composer.json to its original content.
![Capture](https://user-images.githubusercontent.com/54913469/64287582-83c18100-cf79-11e9-8578-793a426f9907.PNG)

**Comment by riteshghimire9090** [comment]
use latest version of laravel
and
composer dump-autoload
