### ISSUE TITLE
how can i change my title desktop notification 

### ISSUE THREAD

**Issue by ibrhaim13** [berkayk/laravel-onesignal#119]
i use 
        \OneSignal::sendNotificationToAll(
                    "Hello",
                     $url = 'https://www.example.com/',
                    $data = [
                        'title'=> 'example',
                        $chrome_big_picture='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQszUqYmRmkzPSIKFtUNhmdIYCsJtTC4CT5N3Vuauw-YqPUB_u6&s',
                     ],
                     $buttons = null,
                    $schedule = null

               );
put the massage notification show laravel

**Comment by berkayk** [comment]
There are many examples written in the tutorial. Please check closed issues as well. Your example code is not a valid PHP code. 

```
$data = [
'title'=> 'example',
$chrome_big_picture='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQszUqYmRmkzPSIKFtUNhmdIYCsJtTC4CT5N3Vuauw-YqPUB_u6&s',
]
``` 
This is not a proper array.
