### ISSUE TITLE
Use variable in array error

### ISSUE THREAD

**Issue by kozguven** [berkayk/laravel-onesignal#120]
Hello,

If I use variable in array I can not send message. If I write email adress in array I can send. Please help me. How can I fix this problem

$bolge_id = Firmalar::find($request['firma_id'])->first()->bolge->id;
            $insaat_mail = Insaat::where('bolge_id', $bolge_id)->first()->mail;
			    OneSignal::sendNotificationUsingTags(
                "TADILAT TALEBI ISTENDI. LUTFEN KONTROL EDINIZ",
                array(
                    ["field"=>"tag","key" => "email", "relation" => "=", "value" => $insaat_mail],

                ),
                $url = null,
                $data = null,
                $buttons = null,
                $schedule = null
            );

**Comment by jmrieger** [comment]
It looks like you've wrapped your array in an array. Try this:


```
$bolge_id = Firmalar::find($request['firma_id'])->first()->bolge->id;
$insaat_mail = Insaat::where('bolge_id', $bolge_id)->first()->mail;
OneSignal::sendNotificationUsingTags(
    "TADILAT TALEBI ISTENDI. LUTFEN KONTROL EDINIZ",
    ["field"=>"tag", "key" => "email", "relation" => "=", "value" => $insaat_mail],
    $url = null,
    $data = null,
    $buttons = null,
    $schedule = null
);
```

**Comment by berkayk** [comment]
Closing due inactivity.
