### ISSUE TITLE
message: "Call to undefined method Berkayk\OneSignal\OneSignalFacade::send()",

### ISSUE THREAD

**Issue by umsuka** [berkayk/laravel-onesignal#121]
Hi Guys

I wanted to check if anyone has experienced this error and how did you solve it.

message: "Call to undefined method Berkayk\OneSignal\OneSignalFacade::send()",
exception: "Symfony\Component\Debug\Exception\FatalThrowableError",

**Comment by WSBrendonBallantyne** [comment]
In my case this error meant that I hadn't used the correct path to the library.
I was able to reference it with just: 

`use OneSignal;`
