### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by rickyjwhong** [berkayk/laravel-onesignal#13]
getting installation error of 

- Can only install one of: symfony/psr-http-message-bridge[v0.2, v1.0.0].
    - Can only install one of: symfony/psr-http-message-bridge[v1.0.0, v0.2].
    - Can only install one of: symfony/psr-http-message-bridge[v0.2, v1.0.0].
    - berkayk/onesignal-laravel v0.9.4 requires symfony/psr-http-message-bridge ^0.2.0 -> satisfiable by symfony/psr-http-message-bridge[v0.2].
    - Installation request for berkayk/onesignal-laravel ^0.9.4 -> satisfiable by berkayk/onesignal-laravel[v0.9.4].
    - Installation request for symfony/psr-http-message-bridge (locked at v1.0.0) -> satisfiable by symfony/psr-http-message-bridge[v1.0.0].

can you bumpt your current psr http message bridge to 1.00? I think the current version of laravel is at conflicting with it.

thanks!

**Comment by rickyjwhong** [comment]
bump :)

**Comment by morganzysman** [comment]
Same issue

**Comment by arietimmerman** [comment]
Same issue here

**Comment by ramisohail** [comment]
whats the solution?

**Comment by abdualrhmanIO** [comment]
me 2

**Comment by ramisohail** [comment]
hi the issue was fixed by requiring
composer require symfony/psr-http-message-bridge
then i changed the version in Composer.json to "^0.2.0",
then Composer update and the plugin installed Successfully.

**Comment by abdualrhmanIO** [comment]
@ramisohail thanks, that's work for me

**Comment by rickyjwhong** [comment]
ya, but other packages such as Laravel passport requires psr 1.0.0 minimum. any reason why you are not upgrading the psr bridge?

**Comment by ramisohail** [comment]
@rickyjwhong its not allowing me if i try to change the version of the psr then it fails when doing composer update with the same error, i want to upgrade to laravel 5.4 and it requires passport 2.0 which which requres psr 1.0.0 and i am stuck right now, i think there should be a permanant solution for this
