### ISSUE TITLE
Client error: `POST https://onesignal.com/api/v1/notifications` resulted in a `400 Bad Request` response: {"errors":["You must include which players, segments, or tags you wish to send this notification to."]}

### ISSUE THREAD

**Issue by dlogvin** [berkayk/laravel-onesignal#134]
I get this error, I do have the users ID and whatever, started to happen right after updating laravel.

**Comment by dlogvin** [comment]
my code looks like this: 

```
OneSignal::sendNotificationToUser(
                    "Your deadline for $task->title is in $diffInDays days",
                    $homework->user->deviceId,
                    $url = null,
                    $data = null,
                    $buttons = null,
                    $schedule = null
                );
```

**Comment by gb9box** [comment]
> my code looks like this:
> 
> ```
> OneSignal::sendNotificationToUser(
>                     "Your deadline for $task->title is in $diffInDays days",
>                     $task->user->deviceId,
>                     $url = null,
>                     $data = null,
>                     $buttons = null,
>                     $schedule = null
>                 );
> ```

Hi @dlogvin ,
I'm getting the same error now.
Could you share me how did you solve this issue?

**Comment by dlogvin** [comment]
This is due to the fact that if you're trying to send to masses, you should make sure all users have the device id, otherwise... you will get the error.

**Comment by gb9box** [comment]
Hi Daniel,

Thanks so much for your quick reply.

Cheers,

**Comment by noumansarwarr** [comment]
> This is due to the fact that if you're trying to send to masses, you should make sure all users have the device id, otherwise... you will get the error.

thnx, but I want to sent onesignal notification only for those which have player_device_id, I have list of users and from that some of don't have a player device id
