### ISSUE TITLE
Laravel 8 is out, needs to upgrade!

### ISSUE THREAD

**Issue by ExpDev07** [berkayk/laravel-onesignal#136]
I have opened a PR which takes care of this: https://github.com/berkayk/laravel-onesignal/pull/135.

**Comment by ahmadeyamin** [comment]
Use 👍 
in composer.json

```json
"repositories": [
        {
            "type": "vcs",
            "url":  "git@github.com:ahmadeyamin/onesignal-laravel.git"
        }
],
"require": {
        "berkayk/onesignal-laravel": "dev-master",
}
```

it will use another forked repo for Laravel 8 support
this is a temporary solution for this repo.

**Comment by ExpDev07** [comment]
@ahmadeyamin pull was merged so shouldn't have to use fork anymore :)
