### ISSUE TITLE
Argument 4 passed to Berkayk\OneSignal\OneSignalClient::Berkayk\OneSignal\{closure}() must be an instance of GuzzleHttp\Exception\RequestException or null, instance of GuzzleHttp\Exception\ConnectException given, RetryMiddleware.php on line 99

### ISSUE THREAD

**Issue by MostafaRabia** [berkayk/laravel-onesignal#143]
Argument 4 passed to Berkayk\OneSignal\OneSignalClient::Berkayk\OneSignal\{closure}() must be an instance of GuzzleHttp\Exception\RequestException or null, instance of GuzzleHttp\Exception\ConnectException given, RetryMiddleware.php on line 99

how to fix it?

**Comment by MostafaHamedAbdelmasoud** [comment]
any solutions?

**Comment by MostafaRabia** [comment]
@MostafaHamedAbdelmasoud 
I knowed it is rejected in egypt, use vpn or use fcm directly, but don't use onesignal in egypt...

**Comment by MostafaHamedAbdelmasoud** [comment]
yes, I am using a VPN, so did you find any solutions for this issue?

**Comment by MostafaRabia** [comment]
@MostafaHamedAbdelmasoud 
i din't use vpn, i used this:
laravel-notification-channels/fcm

**Comment by MostafaRabia** [comment]
@MostafaHamedAbdelmasoud 
I remembered something now, go to `RetryMiddleware.php on line 99` then replace 'ConnectException' by 'RequestException' and try.

**Comment by MostafaHamedAbdelmasoud** [comment]
thanks for your response, but I don't have ConnectException in this file
vendor/guzzlehttp/guzzle/src/RetryMiddleware.php

**Comment by HichemMerniz** [comment]
I have the same error

**Comment by eslamabdallah74** [comment]
I have the same error

**Comment by Nazar531992** [comment]
Hi, I found a solution for anyone interested
go to
vendor -> src -> OneSignalClient.php 

and change API_URL from "https://onesignal.com/api/v1" to "https://app.onesignal.com/api/v1"
