### ISSUE TITLE
how can send android_channel_id ?????????????????

### ISSUE THREAD

**Issue by DeepQservices** [berkayk/laravel-onesignal#145]

**Comment by icangku** [comment]
how u solved this?

**Comment by DeepQservices** [comment]
hello @icangku  here is the code that i have created you have to add parameters like this..
                              $userId = $near_by->device_token;
                              $message1 = "your msg"
                              $params = [];
                             $params['android_channel_id'] ="Your channel id";
                             $params['contents'] ="your message";
                            try {
                                OneSignal::sendNotificationToUser(
                                    $message1,
                                    $userId,
                                    $params,
                                    $url = null
                             
                                );
                            } catch (\Exception $e) {
                             
                            }

**Comment by icangku** [comment]
yeah, I've found the answer before you replied, I just realized, thanks anyway
