### ISSUE TITLE
updating configuration section at readme

### ISSUE THREAD

**Issue by ysupr** [berkayk/laravel-onesignal#15]
in your readme, the configuration are done at config/onesignal.php

> You need to fill in onesignal.php file that is found in your applications config directory. app_id is your OneSignal App ID and rest_api_key is your REST API Key.

but after installed it, the onesignal.php are not used now. 

1. when vendor:publish, it's not included
2. even we set up at onesignal.php, i think your code try to get the config from config/services.php

i tried to setup at config/onesignal.php but it always error, then i moved to config/services.php and it works. 

how about PR about this step at readme?

**Comment by kossa** [comment]
@ysupr for me(using Laravel 5.4) it works fine with config/onesignal.php, and the same for your case :)

in the service provider @berkayk check in config/services.php the onesignal variable, or directly in config.onesignal.php

here is the code : https://github.com/berkayk/laravel-onesignal/blob/master/src/OneSignalServiceProvider.php#L34
