### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by darkperis** [berkayk/laravel-onesignal#157]
Please add support for Laravel 9. Thanks

**Comment by jespejoh** [comment]
Unfortunately it seems it's needed: this package blocks updating to L9 as it requires Guzzle ^6.2 when L9 requires Guzzle ^7.0.

**Comment by MatheusNascimentoti99** [comment]
Is there any solution?

**Comment by mohamed-aiman** [comment]
I have not tested but for now I have created a fork of this repo and I am using it with the required changes. If you want to use it too what you can do is add following to your composer.json

    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/mohamed-aiman/laravel-onesignal"
        }
    ],

after that run

````
composer require berkayk/onesignal-laravel:dev-laravel_9_support
````
This will add ```"berkayk/onesignal-laravel": "dev-laravel_9_support",``` to your composer.json and install it with the changes. I am going to use the package this way till the owner adds the support to Laravel 9.

Feel free to use my fork and request for any necessary changes.
