### ISSUE TITLE
specify icon of notifications

### ISSUE THREAD

**Issue by ysupr** [berkayk/laravel-onesignal#16]
based on onesignal documentation, we can add icon at notification use chrome_web_icon.

i tested to use something like this

`OneSignal::sendNotificationToAll("Some Message", $url, [ 'chrome_web_icon' => $icon_url ] );`

whith $icon_url are the url of icon i want to show, but it's not work. the icon still using default icon at onesignal dashboard. 

Do you have any idea how to set it up?

Thanks

**Comment by diegomengarda** [comment]
Hi @ysupr , i think the correct is 'chrome_big_picture'.

**Comment by ysupr** [comment]
Hi @diegomengarda thanks for follow up, mm i am not sure about it, and i can't re-test it using chrome_big_picture. I ended up using raw PHP Curl because i need some custom features, so again, can't test it more. May next time will use and re-test it. thanks
