### ISSUE TITLE
Include segments broken - Send custom notification

### ISSUE THREAD

**Issue by Sml995** [berkayk/laravel-onesignal#168]
In the last release an additional check is performed before setting `$parameters['included_segments'] = ['All']` by default in `sendNotificationCustom()`

However the check is on the string instead of the array index:
```php
empty('include_external_user_ids')
```
Should be:
```php
empty($parameters['include_external_user_ids'])
```

**Comment by sevak88** [comment]
Any news??((

**Comment by Sml995** [comment]
@berkayk
Would be great to merge that, let us know if you need any help
