### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by infinitypaul** [berkayk/laravel-onesignal#177]
Please add support for Laravel 10. Thanks

**Comment by owenvoke** [comment]
Looks like this was released 👍🏻

**Comment by owenvoke** [comment]
Actually, looks like this was tagged, but isn't showing up on Packagist as the tag wasn't a valid version syntax ([`v.1.10`](https://github.com/berkayk/laravel-onesignal/releases/tag/v.1.10)). Assuming it was meant to be `v1.1.0`? 🤔 Pinging @berkayk, please could a new tag can be created?
