### ISSUE TITLE
Undefined class OneSignal

### ISSUE THREAD

**Issue by ahadabasi** [berkayk/laravel-onesignal#20]
Undefined class OneSignal 

`OneSignal::sendNotificationToAll("Some Message");`

I added this codes to config/app.php

`'providers' => [
    // ...
    Berkayk\OneSignal\OneSignalServiceProvider::class,
];`

and 

`'aliases' => [
    // ...
    'OneSignal' => Berkayk\OneSignal\OneSignalFacade::class,
];`

Also i run this command

`php artisan config:clear`
`php artisan config:cache`

But Undefined class OneSignal, i run `composer dumpauto` command and this worked. I use phpStorm, now i must typed methods name full and phpStorm doesn't complete method names.

**Comment by berkayk** [comment]
I didn't understand your question. Is it working or not?

**Comment by kossa** [comment]
@ahadabasi , you should add `use OneSignal;` at the top of your file ;)

**Comment by ahadabasi** [comment]
Thanks, by add "use OneSignal" this is working.

**Comment by kossa** [comment]
@ahadabasi you can close the issue :)

**Comment by manojrammurthy** [comment]
i am getting Call to undefined function Berkayk\OneSignal\tap()
any reason for this

**Comment by jerearaujo03** [comment]
did you solve it?

**Comment by kossa** [comment]
add "use OneSignal" this is working.

**Comment by jerearaujo03** [comment]
I think it's because I'm working on 5.2, and tap helper is included in Laravel 5.4+.
Is there a workaround for 5.3- ?

**Comment by jerearaujo03** [comment]
I made a workaround, is making a helper function

```
function tap($value, $callback)
{
    $callback($value);
 
    return $value;
}
```

**Comment by siddiqSB** [comment]
function tap($value, $callback)
{
    $callback($value);
 
    return $value;
}
Add this code in vendor\berkayk\onesignal-laravel\src\OneSignalClient.php line : 86

**Comment by Alaa-OmarAlshobaki** [comment]
function tap($value, $callback)
{
$callback($value);
return $value;
}
Add this code in vendor\berkayk\onesignal-laravel\src\OneSignalClient.php line : 86 
I added, but it's not working!

**Comment by fabioselau077** [comment]
same here... Undefined type 'OneSignal'.

**Comment by davide-granello** [comment]
Same here!

I have this error in VSCode: `Undefined type 'OneSignal'.intelephense(P1009)`

```php
use OneSignal;

class SendPushNotification implements ShouldQueue
{

     // ...

     public function handle(): void
     {
         OneSignal::sendNotificationToSegment(
         "Test message with custom heading and subtitle",
         "Testers",
         null,
         null,
         null,
         null,
         "Custom Heading",
         "Custom subtitle"
         );
     }

}
```

@berkayk can this issue be reopened? Or can you provide a solution/suggestions?
Thanks

**Comment by davide-granello** [comment]
> Same here!
> 
> I have this error in VSCode: `Undefined type 'OneSignal'.intelephense(P1009)`
> 
> ```
> use OneSignal;
> 
> class SendPushNotification implements ShouldQueue
> {
> 
>      // ...
> 
>      public function handle(): void
>      {
>          OneSignal::sendNotificationToSegment(
>          "Test message with custom heading and subtitle",
>          "Testers",
>          null,
>          null,
>          null,
>          null,
>          "Custom Heading",
>          "Custom subtitle"
>          );
>      }
> 
> }
> ```
> 
> @berkayk can this issue be reopened? Or can you provide a solution/suggestions? Thanks

Pull request #153 solves this! Please merge it
