### ISSUE TITLE
Specify icon in /res folder

### ISSUE THREAD

**Issue by dayaki** [berkayk/laravel-onesignal#29]
I followed onesignal doc on how to generate custom icon, but am wondering if there is a way to make it use my custom icon sitting in the res/ folder? How do I link to the custom icon inside my app?

**Comment by dakshhmehta** [comment]
I'm not sure whatever I understood your question correctly but. Here is what I did for adding custom icon which is already there in an app.
```php
OneSignal::addParams([
				'small_icon' => 'ic_launcher'
			])->sendNotificationToAll
```

**Comment by dayaki** [comment]
@dakshhmehta where should I  put the "ic_launcher" ?
