### ISSUE TITLE
Support multiple apps?

### ISSUE THREAD

**Issue by almatri** [berkayk/laravel-onesignal#33]
Hi,
I have a website where it should send notifications to two apps.
Each app has its own app_id , rest_api_key , user_auth_key
How can I achieve this??

**Comment by raulamoretti** [comment]
Hi,

I need this too.
How can I send for two app_id?

**Comment by danieluyo** [comment]
Look this
https://github.com/berkayk/laravel-onesignal/issues/2

**Comment by xcesaralejandro** [comment]
Look this

**Comment by Maykonn** [comment]
@xcesaralejandro in https://github.com/berkayk/laravel-onesignal/issues/2 issue you can learn that is necessary create a new instance of `OneSignalClient` for each app.
