### ISSUE TITLE
Add error logging

### ISSUE THREAD

**Issue by zvermafia** [berkayk/laravel-onesignal#34]
Sometimes WEB Push notification aren't coming and I don't know why. Laravel log files are empty, failed queues are empty too. Maybe this package is just hiding errors and doesn't logging...

I don't know how to debug, could you add error logging?

**Comment by Maykonn** [comment]
Your [OneSignal Message Report](https://documentation.onesignal.com/v3.0/docs/notification-delivery) show any error? The notification just will be delivered if sent for GCM, APNS, etc if the notification haven't errors.

Notification not will be received by stopped apps(some devices put apps in stopped state sometimes), [read this:](http://stackoverflow.com/questions/39931562/one-signal-notification-did-not-receive-on-real-device-while-application-is-clos)

**Comment by zvermafia** [comment]
A proplem was in queues (supervisor), still I don't understand why. I tried `queue:restart`, but works only after `supervisorctl restart ...`
