### ISSUE TITLE
add new user

### ISSUE THREAD

**Issue by oliviaaldisa** [berkayk/laravel-onesignal#4]
how to add new user?

**Comment by davorpeic** [comment]
+1

**Comment by Maykonn** [comment]
I'll send a Pull Request soon.

**Comment by designloud** [comment]
+1

**Comment by Maykonn** [comment]
Sorry by delay.

You can use the `createPlayer` and `editPlayer` methods on OneSignalClient.php. Read the docs about params requested to create/edit players: 

[Create](https://documentation.onesignal.com/v3.0/reference#add-a-device)
[Update](https://documentation.onesignal.com/v3.0/reference#edit-device)
