### ISSUE TITLE
sendNotificationUsingTags

### ISSUE THREAD

**Issue by jerson00** [berkayk/laravel-onesignal#42]
Hello, I'm trying to send notifications to tags, but I received the following error message:

 class 'Berkayk\OneSignal\OneSignalClient' does not have a method 'sendNotificationUsingTags'

Regards

**Comment by Chathula** [comment]
use `dev-master` version of package.

put this into `composer.json` and run `composer update`
`"berkayk/onesignal-laravel": "dev-master",`

or you can directly run `composer require berkayk/onesignal-laravel:dev-master`

but there is also a issue in `sendNotificationUsingTags`

i have fixed it in this #PR https://github.com/berkayk/laravel-onesignal/pull/40 (waiting for merge)

**Comment by berkayk** [comment]
This should be fixed in the latest version.
