### ISSUE TITLE
Package broken

### ISSUE THREAD

**Issue by Chathula** [berkayk/laravel-onesignal#44]
PR https://github.com/berkayk/laravel-onesignal/pull/41 breaks the package! please double check!! 

it must use `isset` instead of normal if checking.

```php
// By Sucipto
        if (isset($parameters['api_key'])) {
            $this->headers['headers']['Authorization'] = 'Basic '.$parameters['api_key'];
        }
        // Make sure to use app_id
        if (!isset($parameters['app_id'])) {
            $parameters['app_id'] = $this->appId;
        }
```

**Comment by lordraz0r** [comment]
This is correct but send tags is not working either.

**Comment by Chathula** [comment]
@lordraz0r , it works.. i am already using it.. my PR fixed tags sending issue!

**Comment by berkayk** [comment]
Can you post your request?

**Comment by jordankobellarz** [comment]
@lordraz0r  It worked to me too.

**Comment by seedgabo** [comment]
@lordraz0r maybe is something with the new guzzle

**Comment by alexspi** [comment]
@Chathula  delete
'onesignal' => [ 'app_id' => env('ONESIGNAL_APP_ID'), 'rest_api_key' => env('ONESIGNAL_REST_API_KEY') ],
from config/servises.php
