### ISSUE TITLE
Action Button issue

### ISSUE THREAD

**Issue by princealikhan** [berkayk/laravel-onesignal#46]
The code we merge in below pull request is not present in master can we look into it.

https://github.com/berkayk/laravel-onesignal/pull/30/commits/df9b8ed4735fab26320f4dc7e0f4941a2cb09247

**Comment by berkayk** [comment]
I'm sorry, I didn't understand what you meant.

**Comment by princealikhan** [comment]
there a syntax error in OneSignalClient class we are passing *$buttons
*variable
but checking with *$button (without 's')* can you please have a look.


*Thanks & Regards,*
*Prince Ali Khan*
*Phone, *+91 99 40 619658
princealikhan08@gmail.com || princealikhan08@hotmail.com
*Facebook <http://www.facebook.com/princekhanprofile> || Twitter
<https://twitter.com/princeprofile> *
