### ISSUE TITLE
ErrorException: Undefined index: app_id in /var/www/html/lazysat-laravel/vendor/berkayk/onesignal-laravel/src/OneSignalClient.php:225

### ISSUE THREAD

**Issue by mayank2108** [berkayk/laravel-onesignal#49]
Issue in the latest commit. 0.9.7
Please add a !isset to line 225 on OneSignalClient. As if someone is not sending app_id in parameters in custom notifications, then it is generating undefined index error.

**Comment by daison12006013** [comment]
Very poor implementation, Got the same thing, our prod is now blocked because of this.

Please add isset @ line 255, or please change your properties to use *protected* don't ever ever use *private*, we can't extend your class at all!

**Comment by berkayk** [comment]
Fixed it at the last commit.
