### ISSUE TITLE
php artisan vendor:publish not create the config file

### ISSUE THREAD

**Issue by Maykonn** [berkayk/laravel-onesignal#5]
The command bellow command not generating the configuration file:

```
php artisan vendor:publish
```

**Comment by heggern** [comment]
I faced the same problem.

I made my own file:
`<?php

return [
	'app_id' => 'XXX,
	'rest_api_key' => 'XXX'
];
?>`

**Comment by LtotheWT** [comment]
do u guys faced no onesignal class error?
