### ISSUE TITLE
Error causing Exception when debug is true

### ISSUE THREAD

**Issue by rutkoski** [berkayk/laravel-onesignal#52]
Line 225 of OneSignalClient.php is causing an unwanted Exception (Undefined index: app_id) when debug is true.

```
if (!$parameters['app_id']) {
    $parameters['app_id'] = $this->appId;
}
```

Should it be using is_empty($parameters['app_id']), maybe?

**Comment by magkopian** [comment]
I have the same problem, it appears that the problem has been actually fixed though on 543f042a845569e26680b7204076240c8f61785a 17 days ago.

@rutkoski Would it be possible to create a new point release, so we can receive the fix by doing a `composer update`?

**Comment by mbardelmeijer** [comment]
@berkayk a new release would be much appreciated 👍

**Comment by berkayk** [comment]
@mbardelmeijer created a new release. I was quite busy those times, forgot to publish a new release.
