### ISSUE TITLE
OneSignal Class not found.

### ISSUE THREAD

**Issue by NitinLogiciel** [berkayk/laravel-onesignal#6]
My php artisan vendor:publish commands not creating anything. I added my own onesignal.php file. Now when I call OneSignal::sendNotificationToAll("Some Message"); I amm getting error. The error is : 

FatalErrorException in FeedsAPIController.php line 47:
Class 'Modules\API\Http\Controllers\OneSignal' not found

**Comment by LtotheWT** [comment]
add use OneSignal;

**Comment by guywarner** [comment]
Having the same issue and I do have `use OneSignal;`

**Comment by berkayk** [comment]
Have you added the alias?

    'aliases' => [
         // ...
         'OneSignal' =>      Berkayk\OneSignal\OneSignalFacade::class
     ];
