### ISSUE TITLE
Pass additional data

### ISSUE THREAD

**Issue by joshnissenbaum** [berkayk/laravel-onesignal#60]
How do you pass additional data key/value's or JSON as a parameter?

I tried:

- (object) ['type' => 5]

- "{'type': 5}" (as a string)

- ['type' => 5]

- json_encode(['type' => 5])

Additional data on client side is always undefined

**Comment by stojankukrika** [comment]
@joshnissenbaum did you find solution?

**Comment by stojankukrika** [comment]
To me works this method:
OneSignal::sendNotificationToUser("Some Message", $userId, $url = null, $data = null, $buttons = null, $schedule = null);
and in $data set additional params as array.

**Comment by berkayk** [comment]
Closing the issue due inactivity.

**Comment by channimol** [comment]
@stojankukrika could you show me an example? I could not get it work. I tried this but not working method fail with error 500
```
     OneSignal::sendNotificationToUser(
            "Some Message",
            $user_id,
            $url = null,
            $data = [{type: "test", id: 1, content: "hello"}],
            $buttons = null,
            $schedule = null
        );

```
