### ISSUE TITLE
Where find user_auth_key

### ISSUE THREAD

**Issue by stojankukrika** [berkayk/laravel-onesignal#63]
I can't find user_auth_key. What is it? Where find in in onesignal?

**Comment by josteph** [comment]
Correct, this one needs to be removed from the config file.
Apparently `user_auth_key` is equals to `rest_api_key`

More about it, [here](https://documentation.onesignal.com/docs/accounts-and-keys#section-app-auth-key).

**Comment by stojankukrika** [comment]
TNX. I just test it without this key and it's works so I make you merge request ;)

**Comment by berkayk** [comment]
I will soon remove `user_auth_key` from the package.

**Comment by wout101media** [comment]
Iknow this issue is closed but at the moment i still see user_auth_key being needed in the OneSignalServiceProvider.

So is something wrong on my end or was this never completed?
