### ISSUE TITLE
ClientException

### ISSUE THREAD

**Issue by mawadameshal** [berkayk/laravel-onesignal#66]
ClientException in RequestException.php line 113:
Client error: `POST https://onesignal.com/api/v1/notifications` resulted in a `400 Bad Request` response:
{"errors":["Incorrect player_id format in include_player_ids (not a valid UUID): 86"]}

**Comment by alexspi** [comment]
delete
`'onesignal' => [
        'app_id' => env('ONESIGNAL_APP_ID'),
        'rest_api_key' => env('ONESIGNAL_REST_API_KEY')
    ], `
from config/servises.php

**Comment by mawadameshal** [comment]
this line not appear in servises.php or onesignal.php

**Comment by ra3oul** [comment]
same here

**Comment by berkayk** [comment]
Can you please paste your request code, so I can see what could be causing the problem?

**Comment by mawadameshal** [comment]
ClientException in RequestException.php line 113:
Client error: POST https://onesignal.com/api/v1/notifications resulted in a 400 Bad Request response:
{"errors":["Incorrect player_id format in include_player_ids (not a valid UUID): 86"]}

this is the message appear no code

**Comment by berkayk** [comment]
It appears that you have sent your request with invalid player ids. They should be in UUID format. Can you paste your request code, not the error log.
