### ISSUE TITLE
Cannot set the title

### ISSUE THREAD

**Issue by aconital** [berkayk/laravel-onesignal#68]
I'm trying to set a title for my notification by passing it into $data but it keeps adding the default title.
This is what I'm doing:
`sendNotificationUsingTags($message , array(["key" => "email", "relation" => "=", "value" => $this->email]), $url, ["headings"=>"test"], $buttons = null, $schedule = null);`

also tried this didn't work
`["headings"=>["en"=>'test this']]`

**Comment by berkayk** [comment]
Hi aconital,

You can use `setParam` for setting parameters.

```
$headings = [];
$headings['en'] = 'Your title here';

OneSignal::setParam('headings', $headings)->sendNotificationUsingTags($message, $tags, $url);
```
I am using this method to set title in my project in production.
