### ISSUE TITLE
How to set priority?

### ISSUE THREAD

**Issue by Firman95** [berkayk/laravel-onesignal#69]
Tried with 
```
OneSignal::addParams([
            'priority'=>'high'
        ])->sendNotificationToAll("Some Message high", $url = null, $data = null, $buttons = null, $schedule = null);
```
and 

`OneSignal::sendNotificationToAll("Some Message hiiigh", $url = null, ['priority'=>'high'], $buttons = null, $schedule = null);`

But message still sent without `'priority'='high'` attribute

**Comment by berkayk** [comment]
According to the [documentation](https://documentation.onesignal.com/reference), `priority` is an integer parameter. 

Can you try the code below:

`OneSignal::addParams(['priority' => 10])->sendNotificationToAll("Some Message high");` 

or 

`OneSignal::setParam('priority', 10)->sendNotificationToAll("Some Message high");`

**Comment by berkayk** [comment]
Did this resolve your issue?

**Comment by Firman95** [comment]
Yes I did resolve this issue, thank you
