### ISSUE TITLE
caught (in promise) TypeError

### ISSUE THREAD

**Issue by ToasterKKK** [berkayk/laravel-onesignal#78]
Hello, I'm getting this error which eventually denying the use of it.
Can you fix it ?
```
OneSignal.js:281 Uncaught (in promise) TypeError: Cannot read property 'force' of undefined
    at Function.<anonymous> (OneSignal.js:281)
    at EmailDeviceRecord.js:7
    at Object.next (EmailDeviceRecord.js:7)
    at s (EmailDeviceRecord.js:7)
```

**Comment by LaravDev** [comment]
That's an error from onesignal directly... probably you deleted the user from onesignal panel, to request again for notifications in web, you can access to the console in chrome (if so) and run the audits... that will reset your notifications permisions status...
