### ISSUE TITLE
Cancel scheduled notification

### ISSUE THREAD

**Issue by LaravDev** [berkayk/laravel-onesignal#79]
What would be the proper way to cancel a notification? any ideas? is this included with the package? Thanks in advance

**Comment by LaravDev** [comment]
also, how do you get the notification id of the sent notification? if anyone knows, thanks in advance

**Comment by abdullah7168** [comment]
i saw a method inside the src folder in onesignalclient file, i think we might need to get notifications of the user than delete them but somehow it is giving me an error undefined method.

**Comment by FrancescoMussi** [comment]
I am trying to figure it out too.
Do you have any update?

We could do it with a cURL request, but then there would be no point in using this package. I would prefer to do it the laravel way.

I have opened a ticket about how to get notification id as a response: https://github.com/berkayk/laravel-onesignal/issues/95

**Comment by FrancescoMussi** [comment]
Thank you very much for quick reply!

**Comment by LaravDev** [comment]
> Thank you very much for quick reply!

Sure no problem

**Comment by nwaughachukwuma** [comment]
Just a quick one, what's the shape of a scheduled notification? I mean what parameter does $schedule take? @berkayk
