### ISSUE TITLE
Send to multiple app_id's

### ISSUE THREAD

**Issue by iteearmah** [berkayk/laravel-onesignal#80]
Want to send to my main and subdomains

**Comment by xcesaralejandro** [comment]
+1 Encontraste la solución ?

**Comment by LaravDev** [comment]
you can create a new instance

`$client = new Berkayk\OneSignal\OneSignalClient('app_id', 'rest_api_key', 'user_auth_key');
dd($client->sendNotificationCustom(
        [
            'contents' => [
                "en" => 'Cool works : ' . date('H:i:s')
            ],
            'included_segments' => ['All']

        ]
 ));`

This is answered [Here](https://github.com/berkayk/laravel-onesignal/issues/2)
