### ISSUE TITLE
Fix reader.me

### ISSUE THREAD

**Issue by marcellorg** [berkayk/laravel-onesignal#83]
[https://github.com/berkayk/laravel-onesignal#sending-a-notification-based-on-tagsfilters](url)
Error
array(["field" => "session_count", "relation" => ">", "value" => '2'])

Correct
array(array("field" => "tag", "key" => "user_id", "relation" => "=", "value" => 1))

**Comment by nwaughachukwuma** [comment]
@berkayk the README is very limited and doesn't convey much how to use other parameters like URL, Buttons, data etc. Please provide an example usage of this. Thanks
