### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $appId ]] in class Berkayk\OneSignal\OneSignalClient

### ISSUE THREAD

**Issue by AliBakrOfficial** [berkayk/laravel-onesignal#84]
how to fix it ?

**Comment by farooqahmedkhan** [comment]
You want to initiailize without an appId?

**Comment by mbabker** [comment]
You can't have the `OneSignalClient` injected via the container because the service is only bound with the "onesignal" identifier.  `OneSignalServiceProvider` is missing a `$this->app->alias('onesignal', 'Berkayk\OneSignal\OneSignalClient');` call.

**Comment by vanushwashere** [comment]
Please merge this PR :+1:
