### ISSUE TITLE
How to send aditional parameter on notification

### ISSUE THREAD

**Issue by joefreire** [berkayk/laravel-onesignal#85]
Helo,
I want to send aditional parameters on notification, and when user get notification go to custom route, that is possible?

thanks

**Comment by farooqahmedkhan** [comment]
You can send it in $data variable. Let us know if you need more clarification

**Comment by berkayk** [comment]
Closing due inactivity.

**Comment by nwaughachukwuma** [comment]
@farooqahmedkhan and @berkayk please provide an example on how this can be done
