### ISSUE TITLE
Adding image url

### ISSUE THREAD

**Issue by piercruz** [berkayk/laravel-onesignal#89]
is there any option to add an image as described in the documentation?, unable to pass the variable.

**Comment by farooqahmedkhan** [comment]
You can use method 
`
    // to add custom parameter
   $client->setParam('key', 'value);
   // to send notification
   $client->sendNotificationCustom($params);`

**Comment by piercruz** [comment]
@farooqahmedkhan my problem was solved, I used a custom notification and everything was put there. Thank you for your response and your time.
