### ISSUE TITLE
Class 'Berkayk\\OneSignal' not found

### ISSUE THREAD

**Issue by billy124** [berkayk/laravel-onesignal#93]
I was looking for support with 'Class 'Berkayk\\OneSignal' not found'

had not checked all the existing threads yet but my browser freaked out and made this thread!

just to update I have added the provider and also the aliases, am using Laravel 5.7

**Comment by berkayk** [comment]
Did you put `use OneSignal;` on top of your file.

**Comment by adriangordon1231** [comment]
> 
> 
> Did you put `use OneSignal;` on top of your file.

There is no class registered to that namespace. Only Berkayk\OneSignal

**Comment by adriangordon1231** [comment]
Spoke too soon. It worked despite my ide (phpstorm) complaining.

**Comment by rvkvino** [comment]
Can any one help me on this issue, I'm also facing same issue. I have tried both way importing use OneSignal; and use Berkayk\OneSignal; But still i'm facing the issue like class OneSignal not found error. I'm using lumen 5.8 version.
