### ISSUE TITLE
addParams is not working

### ISSUE THREAD

**Issue by FrancescoMussi** [berkayk/laravel-onesignal#94]
Hello. Great package. It works great.
But I am trying to style the notification and I don't manage.
The notifications keep coming with basic style.

I have tried using `addParams` but it doesn't seems to work.
Also the icon button doesn't work.

Do you know why?

Here is the code:

```
OneSignal::addParams([
    'small_icon' => 'ic_launcher',
    'android_background_layout' => 'https://via.placeholder.com/250'
])->sendNotificationToAll(
    "AppName" . PHP_EOL .
    "Some more text"
    $url = null,
    $data = ['id' => $id],
    $buttons = [["id" => "got_it", "text" => "Got it", "icon" => "https://i.imgur.com/N8SN8ZS.png"]],
    $schedule = null
);
```

**Comment by nwaughachukwuma** [comment]
@berkayk any update on this please?

**Comment by fradrick** [comment]
Any update??

**Comment by nwaughachukwuma** [comment]
Hey @fradrick I got it to work, but didn't revert to update on things. Find below an example configuration with addParams
```           
OneSignal::addParams([
      'send_after'  => now()->addSeconds(30)->toDateTimeString()." UTC+0100", 
      'android_led_color'    => 'FFF67280',
      'android_accent_color' => 'FFF67280',
])->sendNotificationToUser(
      "Custom message",
      $player_id,
      $url      = 'url_to_open_on_button_click, // <--could be a dynamic/deep link
      $data     = ['id' => $id], //<-- customize it as you wish with key-value param, for handling in the app
      $buttons  = [array of buttons or null], // e.g. [["id" => "got_it", "text" => "Got it", "icon" => "https://i.imgur.com/N8SN8ZS.png"]]
      $schedule = null //<-- I configure this using the send_after in addParams array
);
```

You can find more information here: https://documentation.onesignal.com/reference#create-notification.

@FrancescoMussi, to create an icon you can find the steps here: https://documentation.onesignal.com/docs/android-customizations#section-small-notification-icons and it should work. Anyone who needs more info can check the create-notification link above for customisation options.

I hope this helps
